global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using Everywhere.Extensions;
global using Everywhere.I18N;
global using LocaleKey = Everywhere.Abstractions.I18N.LocaleKey;
global using LocaleResolver = Everywhere.Abstractions.I18N.LocaleResolver;
