using Everywhere.Common;
using Lucide.Avalonia;

namespace Everywhere.StrategyEngine;

/// <summary>
/// A command that can be executed by the Strategy Engine.
/// Commands are generated by strategies based on the current context.
/// </summary>
public sealed record StrategyCommand
{
    /// <summary>
    /// Unique identifier for deduplication across strategies.
    /// </summary>
    public required string Id { get; init; }

    /// <summary>
    /// Display name.
    /// </summary>
    public required IDynamicResourceKey Name { get; init; }

    /// <summary>
    /// Optional description shown as tooltip or subtitle.
    /// </summary>
    public IDynamicResourceKey? Description { get; init; }

    /// <summary>
    /// Icon for UI display.
    /// </summary>
    public ColoredIcon? Icon { get; init; } = LucideIconKind.Sparkles;

    /// <summary>
    /// Priority for sorting (higher = more prominent position).
    /// </summary>
    public int Priority { get; init; }

    /// <summary>
    /// System prompt template for the agent session. Overrides the default prompt.
    /// Supports variable interpolation with {{variable}} syntax.
    /// </summary>
    public string? SystemPrompt { get; init; }

    /// <summary>
    /// User message template to auto-send when starting the conversation.
    /// Supports variable interpolation with {{variable}} syntax.
    /// </summary>
    public string? UserMessage { get; init; }

    /// <summary>
    /// Allowed tool/plugin names for this command.
    /// null = use default tools, empty = no tools allowed.
    /// </summary>
    public IReadOnlyList<string>? AllowedTools { get; init; }

    /// <summary>
    /// Variables for prompt template interpolation.
    /// These are resolved at execution time from the context.
    /// </summary>
    public IReadOnlyDictionary<string, object>? Variables { get; init; }
}