using Everywhere.Common;
using Lucide.Avalonia;
using MessagePack;

namespace Everywhere.StrategyEngine;

/// <summary>
/// A command that can be executed by the Strategy Engine.
/// Commands are generated by strategies based on the current context.
/// </summary>
[MessagePackObject(OnlyIncludeKeyedMembers = true, AllowPrivate = true)]
public sealed partial record StrategyCommand
{
    /// <summary>
    /// Unique identifier for deduplication across strategies.
    /// </summary>
    [Key(0)] public required string Id { get; init; }

    /// <summary>
    /// Display name.
    /// </summary>
    [Key(1)] public required IDynamicResourceKey NameKey { get; init; }

    /// <summary>
    /// Optional description shown as tooltip or subtitle.
    /// </summary>
    public IDynamicResourceKey? DescriptionKey { get; init; }

    /// <summary>
    /// Icon for UI display.
    /// </summary>
    public ColoredIcon? Icon { get; init; } = LucideIconKind.Sparkles;

    /// <summary>
    /// Priority for sorting (higher = more prominent position).
    /// </summary>
    public int Priority { get; init; }

    /// <summary>
    /// System prompt template for the agent session. Overrides the default prompt.
    /// Supports variable interpolation with {variable} syntax.
    /// TODO: Use {SystemPrompt} for the original system prompt.
    /// Leave null to use the default system prompt.
    /// </summary>
    [Key(2)] public string? SystemPrompt { get; init; }

    /// <summary>
    /// User message template to auto-send when starting the conversation.
    /// Supports variable interpolation with {variable} syntax.
    /// TODO: Use {Argument} for Argument
    /// </summary>
    [Key(3)] public string? UserMessage { get; init; }

    /// <summary>
    /// Allowed tool/plugin names for this command.
    /// null = use default tools, empty = no tools allowed.
    /// </summary>
    [Key(4)] public IReadOnlyList<string>? AllowedTools { get; init; }

    /// <summary>
    /// Displays in the watermark as a hint for the user input after selecting this command.
    /// </summary>
    public IDynamicResourceKey? ArgumentHintKey { get; init; }
}